### ISSUE TITLE
Missing code/files in released version 1.3.0

### ISSUE THREAD

**Issue by akiessling** [websedit/we_cookie_consent#1]
In the latest TER release (1.3.0) the folders Classes, Configuration and Resources are empty.

**Comment by steinbinder** [comment]
@akiessling Thank you very much for the hint! I have now uploaded version 1.3.1 to TER. Could you please try it again?

I have noticed that the zip file cannot be unzipped properly after downloading it from the TER website. However, the installation via the extensionmanager in the TYPO3 Backend works. 

Have you downloaded from TER websedit or via the extensionmanager?

I can't figure out the problem yet. I have created the zip file the same way as with the previous versions. I'm downloading the new version of the extension as ZIP via extensionmanager, rename the file and reupload it via TER website.

**Comment by akiessling** [comment]
I had it installed via composer typo3-ter/we-cookie-consent - but switched that now to websedit/we-cookie-consent as that package did not have the error.
Manual unzip on the commandline works for me with 1.3.1, but my gui app Keka on MacOS reports a fatal error. 
My collegue could open it in Ubuntu without a problem.

**Comment by steinbinder** [comment]
My colleague was also able to unzip the file in Windows. So no problems there.

I have uploaded version 1.3.2. I have now generated the ZIP file via the commandline, unfortunately the problem still seems to exist (on macOS).

I'll leave the ticket open for now and have a look at it again with the next release or contact a TER member, because I don't want to push more useless versions in TER for debugging the Error. 

Thank's for your support so far @akiessling.

For all those who have the same problem, please install directly via the extensionmanager in backend, via the composer package `websedit/we-cookie-consent` or use the version from this GIT repositry.

**Comment by akiessling** [comment]
It seems like the files are extracted with wrong permissions. unzip shows, that the files are extracted:
```
❯ unzip we_cookie_consent_1.3.2.zip
Archive:  we_cookie_consent_1.3.2.zip
  inflating: changelog.txt           
   creating: Classes/
   creating: Classes/Hook/
  inflating: Classes/Hook/AfterSaveHook.php  
```

```
❯ ls -al Classes
❯ sudo ls -al Classes
total 0
drw-rw-rw-@  6 andreas  staff  192 20 Aug 18:09 .
drwxr-xr-x  19 andreas  staff  608 21 Aug 10:24 ..
drw-rw-rw-@  4 andreas  staff  128 20 Aug 18:09 Controller
drw-rw-rw-@  4 andreas  staff  128 20 Aug 18:09 Domain
drw-rw-rw-@  3 andreas  staff   96 20 Aug 18:09 Hook
drw-rw-rw-@  6 andreas  staff  192 20 Aug 18:09 ViewHelpers
```

I'm not sure what composer uses to extract the files on my machine, i have the same error with e.g. https://extensions.typo3.org/extension/ce_timeline/ - so it seems to be an error at another level.

**Comment by steinbinder** [comment]
It seams that this is fixed now. So I close this ticket. Thank you for your support and help.
